/** ISO 3166-1 alpha-2 country code → continent (for location suggestions). */
const CONTINENT_BY_COUNTRY: Record<string, string> = {
  ad: "Europe",
  ae: "Asia",
  af: "Asia",
  ag: "North America",
  al: "Europe",
  am: "Asia",
  ao: "Africa",
  ar: "South America",
  at: "Europe",
  au: "Oceania",
  az: "Asia",
  ba: "Europe",
  bb: "North America",
  bd: "Asia",
  be: "Europe",
  bf: "Africa",
  bg: "Europe",
  bh: "Asia",
  bi: "Africa",
  bj: "Africa",
  bn: "Asia",
  bo: "South America",
  br: "South America",
  bs: "North America",
  bt: "Asia",
  bw: "Africa",
  by: "Europe",
  bz: "North America",
  ca: "North America",
  cd: "Africa",
  cf: "Africa",
  cg: "Africa",
  ch: "Europe",
  ci: "Africa",
  cl: "South America",
  cm: "Africa",
  cn: "Asia",
  co: "South America",
  cr: "North America",
  cu: "North America",
  cv: "Africa",
  cy: "Asia",
  cz: "Europe",
  de: "Europe",
  dj: "Africa",
  dk: "Europe",
  dm: "North America",
  do: "North America",
  dz: "Africa",
  ec: "South America",
  ee: "Europe",
  eg: "Africa",
  er: "Africa",
  es: "Europe",
  et: "Africa",
  fi: "Europe",
  fj: "Oceania",
  fr: "Europe",
  ga: "Africa",
  gb: "Europe",
  gd: "North America",
  ge: "Asia",
  gh: "Africa",
  gm: "Africa",
  gn: "Africa",
  gq: "Africa",
  gr: "Europe",
  gt: "North America",
  gw: "Africa",
  gy: "South America",
  hk: "Asia",
  hn: "North America",
  hr: "Europe",
  ht: "North America",
  hu: "Europe",
  id: "Asia",
  ie: "Europe",
  il: "Asia",
  in: "Asia",
  iq: "Asia",
  ir: "Asia",
  is: "Europe",
  it: "Europe",
  jm: "North America",
  jo: "Asia",
  jp: "Asia",
  ke: "Africa",
  kg: "Asia",
  kh: "Asia",
  km: "Africa",
  kn: "North America",
  kp: "Asia",
  kr: "Asia",
  kw: "Asia",
  kz: "Asia",
  la: "Asia",
  lb: "Asia",
  lc: "North America",
  lk: "Asia",
  lr: "Africa",
  ls: "Africa",
  lt: "Europe",
  lu: "Europe",
  lv: "Europe",
  ly: "Africa",
  ma: "Africa",
  mc: "Europe",
  md: "Europe",
  me: "Europe",
  mg: "Africa",
  mk: "Europe",
  ml: "Africa",
  mm: "Asia",
  mn: "Asia",
  mo: "Asia",
  mr: "Africa",
  mt: "Europe",
  mu: "Africa",
  mv: "Asia",
  mw: "Africa",
  mx: "North America",
  my: "Asia",
  mz: "Africa",
  na: "Africa",
  ne: "Africa",
  ng: "Africa",
  ni: "North America",
  nl: "Europe",
  no: "Europe",
  np: "Asia",
  nz: "Oceania",
  om: "Asia",
  pa: "North America",
  pe: "South America",
  pg: "Oceania",
  ph: "Asia",
  pk: "Asia",
  pl: "Europe",
  pr: "North America",
  ps: "Asia",
  pt: "Europe",
  py: "South America",
  qa: "Asia",
  ro: "Europe",
  rs: "Europe",
  ru: "Europe",
  rw: "Africa",
  sa: "Asia",
  sb: "Oceania",
  sc: "Africa",
  sd: "Africa",
  se: "Europe",
  sg: "Asia",
  si: "Europe",
  sk: "Europe",
  sl: "Africa",
  sm: "Europe",
  sn: "Africa",
  so: "Africa",
  sr: "South America",
  ss: "Africa",
  st: "Africa",
  sv: "North America",
  sy: "Asia",
  sz: "Africa",
  td: "Africa",
  tg: "Africa",
  th: "Asia",
  tj: "Asia",
  tm: "Asia",
  tn: "Africa",
  to: "Oceania",
  tr: "Asia",
  tt: "North America",
  tw: "Asia",
  tz: "Africa",
  ua: "Europe",
  ug: "Africa",
  us: "North America",
  uy: "South America",
  uz: "Asia",
  vc: "North America",
  ve: "South America",
  vn: "Asia",
  vu: "Oceania",
  ws: "Oceania",
  ye: "Asia",
  za: "Africa",
  zm: "Africa",
  zw: "Africa",
};

export function continentForCountryCode(countryCode?: string) {
  if (!countryCode) return "Unknown";
  return CONTINENT_BY_COUNTRY[countryCode.toLowerCase()] ?? "Unknown";
}
