import type { DiscoverJob, JobApplication } from "./types";

export const MOCK_APPLICATIONS: JobApplication[] = [
  {
    id: "1",
    company: "Stripe",
    title: "Software Engineer",
    location: "San Francisco, CA",
    source: "linkedin",
    status: "technical",
    appliedAt: "2026-06-01",
    salary: "$140k–$180k",
    url: "https://stripe.com/jobs",
    companyDomain: "stripe.com",
  },
  {
    id: "2",
    company: "Notion",
    title: "Frontend Engineer",
    location: "New York, NY",
    source: "handshake",
    status: "applied",
    appliedAt: "2026-06-05",
    salary: "$130k–$165k",
    url: "https://notion.so/careers",
    companyDomain: "notion.so",
  },
  {
    id: "3",
    company: "Airbnb",
    title: "Full Stack Developer",
    location: "Remote",
    source: "indeed",
    status: "rejected",
    appliedAt: "2026-05-20",
    salary: "$125k–$160k",
    url: "https://careers.airbnb.com",
    companyDomain: "airbnb.com",
  },
  {
    id: "4",
    company: "Figma",
    title: "Product Engineer",
    location: "San Francisco, CA",
    source: "linkedin",
    status: "offer",
    appliedAt: "2026-04-15",
    salary: "$155k–$190k",
    url: "https://figma.com/careers",
    companyDomain: "figma.com",
  },
  {
    id: "5",
    company: "Shopify",
    title: "Backend Engineer",
    location: "Remote",
    source: "handshake",
    status: "phone_screen",
    appliedAt: "2026-06-10",
    salary: "$135k–$170k",
    url: "https://shopify.com/careers",
    companyDomain: "shopify.com",
  },
  {
    id: "6",
    company: "Datadog",
    title: "Software Engineer II",
    location: "Boston, MA",
    source: "indeed",
    status: "onsite",
    appliedAt: "2026-05-28",
    salary: "$130k–$165k",
    url: "https://careers.datadoghq.com",
    companyDomain: "datadoghq.com",
  },
  {
    id: "7",
    company: "Linear",
    title: "Design Engineer",
    location: "Remote",
    source: "manual",
    status: "final_round",
    appliedAt: "2026-05-12",
    salary: "$140k–$175k",
    url: "https://linear.app/careers",
    companyDomain: "linear.app",
  },
  {
    id: "8",
    company: "Vercel",
    title: "Developer Advocate",
    location: "Remote",
    source: "linkedin",
    status: "accepted",
    appliedAt: "2026-03-01",
    salary: "$120k–$150k",
    url: "https://vercel.com/careers",
    companyDomain: "vercel.com",
  },
  {
    id: "9",
    company: "Acme Labs",
    title: "Junior Developer",
    location: "Portland, OR",
    source: "manual",
    status: "applied",
    appliedAt: "2026-06-15",
    salary: "$75k–$90k",
  },
  {
    id: "10",
    company: "Anthropic",
    title: "ML Infrastructure Engineer",
    location: "San Francisco, CA",
    source: "linkedin",
    status: "phone_screen",
    appliedAt: "2026-06-12",
    salary: "$180k–$250k",
    url: "https://anthropic.com/careers",
    companyDomain: "anthropic.com",
  },
  {
    id: "11",
    company: "Spotify",
    title: "Senior iOS Engineer",
    location: "New York, NY",
    source: "handshake",
    status: "technical",
    appliedAt: "2026-06-08",
    salary: "$160k–$210k",
    url: "https://lifeatspotify.com",
    companyDomain: "spotify.com",
  },
  {
    id: "12",
    company: "Cloudflare",
    title: "Systems Engineer",
    location: "Austin, TX",
    source: "indeed",
    status: "applied",
    appliedAt: "2026-06-14",
    salary: "$140k–$185k",
    url: "https://cloudflare.com/careers",
    companyDomain: "cloudflare.com",
  },
  {
    id: "13",
    company: "Ramp",
    title: "Full Stack Engineer",
    location: "New York, NY",
    source: "linkedin",
    status: "onsite",
    appliedAt: "2026-05-30",
    salary: "$150k–$200k",
    url: "https://ramp.com/careers",
    companyDomain: "ramp.com",
  },
  {
    id: "14",
    company: "Discord",
    title: "Backend Engineer",
    location: "San Francisco, CA",
    source: "discover",
    status: "final_round",
    appliedAt: "2026-05-22",
    salary: "$155k–$195k",
    url: "https://discord.com/careers",
    companyDomain: "discord.com",
  },
  {
    id: "15",
    company: "Canva",
    title: "Frontend Engineer",
    location: "Remote",
    source: "discover",
    status: "applied",
    appliedAt: "2026-06-16",
    salary: "$120k–$160k",
    url: "https://canva.com/careers",
    companyDomain: "canva.com",
  },
  {
    id: "16",
    company: "GitHub",
    title: "Staff Engineer",
    location: "Remote",
    source: "linkedin",
    status: "withdrawn",
    appliedAt: "2026-04-20",
    salary: "$190k–$240k",
    url: "https://github.com/careers",
    companyDomain: "github.com",
  },
  {
    id: "17",
    company: "Netflix",
    title: "Senior Software Engineer",
    location: "Los Gatos, CA",
    source: "indeed",
    status: "rejected",
    appliedAt: "2026-05-05",
    salary: "$200k–$280k",
    url: "https://jobs.netflix.com",
    companyDomain: "netflix.com",
  },
  {
    id: "18",
    company: "Retool",
    title: "Product Engineer",
    location: "San Francisco, CA",
    source: "handshake",
    status: "offer",
    appliedAt: "2026-04-28",
    salary: "$145k–$185k",
    url: "https://retool.com/careers",
    companyDomain: "retool.com",
  },
  {
    id: "19",
    company: "Brex",
    title: "Platform Engineer",
    location: "Remote",
    source: "manual",
    status: "phone_screen",
    appliedAt: "2026-06-11",
    salary: "$150k–$195k",
    url: "https://brex.com/careers",
    companyDomain: "brex.com",
  },
  {
    id: "20",
    company: "Plaid",
    title: "Backend Engineer II",
    location: "San Francisco, CA",
    source: "linkedin",
    status: "technical",
    appliedAt: "2026-06-03",
    salary: "$155k–$200k",
    url: "https://plaid.com/careers",
    companyDomain: "plaid.com",
  },
];

export const MOCK_DISCOVER_JOBS: DiscoverJob[] = [
  {
    id: "d1",
    company: "Anthropic",
    title: "ML Infrastructure Engineer",
    location: "San Francisco, CA",
    salary: "$180k–$250k",
    description:
      "Build scalable infrastructure for training and serving large language models. Work with a world-class research team.",
    tags: ["Python", "Kubernetes", "ML"],
    remote: false,
    employmentType: "Full-time",
    benefits: ["Equity", "Health Insurance", "Visa Sponsorship"],
    postedAt: "2026-06-18",
    url: "https://anthropic.com/careers",
    companyDomain: "anthropic.com",
  },
  {
    id: "d2",
    company: "Spotify",
    title: "Senior iOS Engineer",
    location: "New York, NY",
    salary: "$160k–$210k",
    description:
      "Shape the listening experience for millions of users. Lead feature development on the Spotify iOS app.",
    tags: ["Swift", "SwiftUI", "Mobile"],
    remote: false,
    employmentType: "Full-time",
    benefits: ["Equity", "Parental Leave", "Learning Budget"],
    postedAt: "2026-06-17",
    url: "https://lifeatspotify.com",
    companyDomain: "spotify.com",
  },
  {
    id: "d3",
    company: "Cloudflare",
    title: "Systems Engineer",
    location: "Austin, TX",
    salary: "$140k–$185k",
    description:
      "Help build the network that powers the internet. Work on edge computing and global infrastructure.",
    tags: ["Rust", "Go", "Networking"],
    remote: true,
    employmentType: "Full-time",
    benefits: ["Remote", "Equity", "401(k) Match"],
    postedAt: "2026-06-16",
    url: "https://cloudflare.com/careers",
    companyDomain: "cloudflare.com",
  },
  {
    id: "d4",
    company: "Ramp",
    title: "Full Stack Engineer",
    location: "New York, NY",
    salary: "$150k–$200k",
    description:
      "Join a fast-growing fintech startup. Build features that help businesses save time and money.",
    tags: ["TypeScript", "React", "PostgreSQL"],
    remote: false,
    employmentType: "Full-time",
    benefits: ["Equity", "Unlimited PTO", "Commuter Benefits"],
    postedAt: "2026-06-15",
    url: "https://ramp.com/careers",
    companyDomain: "ramp.com",
  },
  {
    id: "d5",
    company: "Discord",
    title: "Backend Engineer",
    location: "San Francisco, CA",
    salary: "$155k–$195k",
    description:
      "Scale real-time messaging for hundreds of millions of users. Work on low-latency distributed systems.",
    tags: ["Elixir", "Rust", "Distributed Systems"],
    remote: true,
    employmentType: "Full-time",
    benefits: ["Remote", "Equity", "Visa Sponsorship"],
    postedAt: "2026-06-14",
    url: "https://discord.com/careers",
    companyDomain: "discord.com",
  },
  {
    id: "d6",
    company: "Canva",
    title: "Frontend Engineer",
    location: "Sydney, Australia",
    salary: "$120k–$160k AUD",
    description:
      "Build creative tools used by billions. Focus on performance, accessibility, and delightful UX.",
    tags: ["React", "TypeScript", "Canvas"],
    remote: true,
    employmentType: "Full-time",
    benefits: ["Remote", "Equity", "Wellness Allowance"],
    postedAt: "2026-06-13",
    url: "https://canva.com/careers",
    companyDomain: "canva.com",
  },
];
