import type { DiscoverJob, IntegrationProvider, JobApplication } from "@/lib/types";
import { MOCK_APPLICATIONS } from "@/lib/mock-data";

export const DEMO_PLATFORM_JOBS: Record<IntegrationProvider, DiscoverJob[]> = {
  handshake: [
    {
      id: "hs-j1",
      source: "handshake",
      company: "Palantir",
      title: "Forward Deployed Engineer",
      location: "Denver, CO",
      salary: "$110k–$140k",
      description:
        "Campus recruiting role working directly with government and commercial customers on mission-critical software.",
      tags: ["Java", "Python", "Campus"],
      remote: false,
      employmentType: "Full-time",
      benefits: ["Relocation", "Health Insurance"],
      postedAt: "2026-06-19",
      url: "https://joinhandshake.com",
      companyDomain: "palantir.com",
    },
    {
      id: "hs-j2",
      source: "handshake",
      company: "Deloitte",
      title: "Technology Analyst",
      location: "Chicago, IL",
      salary: "$85k–$95k",
      description:
        "Consulting technology track for new grads. Rotations across cloud, data, and engineering projects.",
      tags: ["Consulting", "Cloud", "Campus"],
      remote: false,
      employmentType: "Full-time",
      postedAt: "2026-06-18",
      url: "https://joinhandshake.com",
      companyDomain: "deloitte.com",
    },
    {
      id: "hs-j3",
      source: "handshake",
      company: "Tesla",
      title: "Software Engineer Intern",
      location: "Palo Alto, CA",
      salary: "$45/hr",
      description: "Summer internship on vehicle software teams. Strong C++ and systems background preferred.",
      tags: ["C++", "Embedded", "Internship"],
      remote: false,
      employmentType: "Internship",
      postedAt: "2026-06-17",
      url: "https://joinhandshake.com",
      companyDomain: "tesla.com",
    },
  ],
  linkedin: [
    {
      id: "li-j1",
      source: "linkedin",
      company: "Meta",
      title: "Software Engineer, Product",
      location: "Menlo Park, CA",
      salary: "$150k–$210k",
      description:
        "Easy Apply role building consumer products at scale. React, GraphQL, and mobile experience a plus.",
      tags: ["React", "GraphQL", "Easy Apply"],
      remote: false,
      employmentType: "Full-time",
      benefits: ["Equity", "Parental Leave"],
      postedAt: "2026-06-19",
      url: "https://linkedin.com/jobs",
      companyDomain: "meta.com",
    },
    {
      id: "li-j2",
      source: "linkedin",
      company: "Snowflake",
      title: "Backend Engineer",
      location: "Remote",
      salary: "$160k–$200k",
      description: "Distributed systems role on the data cloud platform. Remote-friendly within the US.",
      tags: ["Distributed Systems", "Java", "Remote"],
      remote: true,
      employmentType: "Full-time",
      postedAt: "2026-06-18",
      url: "https://linkedin.com/jobs",
      companyDomain: "snowflake.com",
    },
    {
      id: "li-j3",
      source: "linkedin",
      company: "Coinbase",
      title: "Full Stack Engineer",
      location: "Remote",
      salary: "$140k–$185k",
      description: "Build trading and wallet experiences. TypeScript across web and API surfaces.",
      tags: ["TypeScript", "React", "Easy Apply"],
      remote: true,
      employmentType: "Full-time",
      postedAt: "2026-06-16",
      url: "https://linkedin.com/jobs",
      companyDomain: "coinbase.com",
    },
  ],
  indeed: [
    {
      id: "in-j1",
      source: "indeed",
      company: "Target",
      title: "Software Engineer I",
      location: "Minneapolis, MN",
      salary: "$95k–$120k",
      description: "Retail technology team building checkout and fulfillment systems.",
      tags: ["Java", "Kotlin", "Retail"],
      remote: false,
      employmentType: "Full-time",
      postedAt: "2026-06-19",
      url: "https://indeed.com",
      companyDomain: "target.com",
    },
    {
      id: "in-j2",
      source: "indeed",
      company: "Capital One",
      title: "Associate Software Engineer",
      location: "McLean, VA",
      salary: "$100k–$130k",
      description: "Entry-level engineering on cloud-native banking products. Indeed Apply supported.",
      tags: ["AWS", "Python", "Indeed Apply"],
      remote: false,
      employmentType: "Full-time",
      benefits: ["401(k)", "Tuition Assistance"],
      postedAt: "2026-06-17",
      url: "https://indeed.com",
      companyDomain: "capitalone.com",
    },
    {
      id: "in-j3",
      source: "indeed",
      company: "Zillow",
      title: "Frontend Engineer",
      location: "Seattle, WA",
      salary: "$130k–$165k",
      description: "Home search and agent tools. React, TypeScript, and design systems experience.",
      tags: ["React", "TypeScript", "Indeed Apply"],
      remote: true,
      employmentType: "Full-time",
      postedAt: "2026-06-15",
      url: "https://indeed.com",
      companyDomain: "zillow.com",
    },
  ],
};

export function getDemoApplications(provider: IntegrationProvider): JobApplication[] {
  return MOCK_APPLICATIONS.filter((app) => app.source === provider).map((app) => ({
    ...app,
    id: `${provider}-${app.id}`,
  }));
}

export function getDemoAvailableJobs(provider: IntegrationProvider): DiscoverJob[] {
  return DEMO_PLATFORM_JOBS[provider];
}
